删除这个项目
    error: 'woo' is not a valid command.
error: Unrecognized command 'woo'.
error: 'woo' is not a valid command.
error: Unrecognized command 'woo'.
2016-03-03 12:38:22.370 WeChatArticle[4004:99249] *** Terminating app
due to uncaught exception 'NSInvalidArgumentException', reason: 'Could
not find a storyboard named 'Main' in bundle NSBundle
</Users/broven/Library/Developer/CoreSimulator/Devices/D4717A1F-3629-4FC
A-BB03-EC144864EC8A/data/Containers/Bundle/Application/2F5DA2C8-8A89-454
7-BDDD-C444540E1167/WeChatArticle.app> (loaded)'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010d561e65
__exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010f2a1deb
objc_exception_throw + 48
	2   UIKit                               0x000000010e4a2669
-[UIStoryboard name] + 0
	3   UIKit                               0x000000010dd7df82
-[UIApplication _loadMainStoryboardFileNamed:bundle:] + 58
	4   UIKit                               0x000000010dd7e2d6
-[UIApplication _loadMainInterfaceFile] + 260
	5   UIKit                               0x000000010dd7cb54
-[UIApplication _runWithMainScene:transitionContext:completion:] + 1390
	6   UIKit                               0x000000010dd79e7b
-[UIApplication workspaceDidEndTransaction:] + 188
	7   FrontBoardServices                  0x0000000114941754
-[FBSSerialQueue _performNext] + 192
	8   FrontBoardServices                  0x0000000114941ac2
-[FBSSerialQueue _performNextFromRunLoopSource] + 45
	9   CoreFoundation                      0x000000010d48da31
__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	10  CoreFoundation                      0x000000010d48395c
__CFRunLoopDoSources0 + 556
	11  CoreFoundation                      0x000000010d482e13
__CFRunLoopRun + 867
	12  CoreFoundation                      0x000000010d482828
CFRunLoopRunSpecific + 488
	13  UIKit                               0x000000010dd797cd
-[UIApplication _run] + 402
	14  UIKit                               0x000000010dd7e610
UIApplicationMain + 171
	15  WeChatArticle                       0x000000010cdf27dd main + 109
	16  libdyld.dylib                       0x00000001106fa92d start + 1
	17  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException